carbonrelay:
  image: nuancemobility/carbon
  restart: always
  command: relay
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  ports:
   - "2003:2003"
   - "2004:2004"
  volumes:
   - ./carbon/relay:/etc/carbon
  links:
   - carboncache1
   - carboncache2

carboncache1:
  image: nuancemobility/carbon
  restart: always
  command: cache
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  volumes:
   - ./carbon/cache:/etc/carbon
  volumes_from:
   - heramonitoring_whisper_1

carboncache2:
  image: nuancemobility/carbon
  restart: always
  command: cache
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  volumes:
   - ./carbon/cache:/etc/carbon
  volumes_from:
   - heramonitoring_whisper_1

graphite:
  image: nuancemobility/graphite-web
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  volumes:
   - ./graphite-web:/etc/graphite
  volumes_from:
   - heramonitoring_whisper_1
  links:
   - carboncache1
   - carboncache2

elasticsearch:
  image: elasticsearch:1.6
  restart: always
  command: -Des.node.name="hera_elasticsearch_001"
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  environment:
   - ES_HEAP_SIZE=512m
  volumes_from:
   - heramonitoring_elasticsearchdata_1

elasticsearchcurator:
  image: nuancemobility/elasticsearch-curator
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  links:
   - elasticsearch
  volumes:
   - ./elasticsearch-curator:/config

grafana:
  image: nuancemobility/grafana
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  volumes:
   - ./grafana/config.js:/usr/share/grafana/config.js

kibana3:
  image: nuancemobility/kibana
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  volumes:
   - ./kibana:/config

logstash:
  image: logstash:1.5.2
  command: -f /config-dir/
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  links:
   - elasticsearch
  volumes:
   - ./logstash/config:/config-dir
   - ./mib:/mib
   - /etc/hera/logstash/ssl:/etc/pki/tls
  ports:
   - "5000:5000/udp"
   - "5001:5001"

sensu:
  image: nuancemobility/sensu
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  links:
   - carbonrelay
   - rabbitmq
  volumes:
   - ./sensu/config:/etc/sensu/conf.d
   - ./sensu/handlers:/etc/sensu/handlers

uchiwa:
  image: uchiwa/uchiwa
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  links:
   - sensu
  volumes:
   - ./uchiwa:/config
  ports:
   - "3030:3000"

sensuclient:
  image: nuancemobility/sensu-client
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  links:
   - rabbitmq
   - sensu
   - graphite
   - screenshoter
  volumes:
   - ./sensu-client/config:/etc/sensu/conf.d
   - ./sensu-client/plugins:/etc/sensu/plugins
   - ./mib:/etc/sensu/mib

cadvisor:
  image: google/cadvisor:0.15.1
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro

monitoringproxy:
  image: nuancemobility/nginx
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  links:
   - uchiwa
   - grafana
   - kibana3
   - elasticsearch
   - cadvisor
   - graphite
   - configsynchronizer
   - screenshoter
  volumes:
   - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
   - ./nginx/html:/usr/share/nginx/html
   - /etc/hera/nginx/includes:/etc/nginx/includes
   - /etc/hera/nginx/ssl:/etc/nginx/ssl
  ports:
   - "443:443"
   - "8080:8080"
   - "4242:4242"

configsynchronizer:
  image: nuancemobility/hera-config-synchronizer
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  links:
   - elasticsearch
  environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200/
   - GIT_REPOSITORY=https://github.com/bargenson/hera-dashboards.git

screenshoter:
  image: nuancemobility/web-screenshoter
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"

rabbitmq:
  image: rabbitmq:3.5
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "50m"
    max-file: "100"
  ports:
   - "5672:5672"

